name: Install verilator
on:
  workflow_call:
runs:
  steps:
    - name: Install verilator
      run: |
        sudo apt-get -y install verilator
        verilator --version
        sudo apt-get -y remove verilator
        git clone https://github.com/verilator/verilator
        cd verilator
        git checkout v5.016
        git clone https://github.com/westes/flex .flex
        cd .flex
        git checkout v2.6.4
        cd ..
        cp .flex/src/FlexLexer.h include/FlexLexer.h
        cp .flex/src/FlexLexer.h FlexLexer.h
        unset VERILATOR_ROOT
        autoconf
        ./configure
        make
        sudo make install