on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  riscv-tests-mi-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_iverilog.yml
      - name: Test
        run: |
          cd test && python3 test.py mi-p-
  riscv-tests-si-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_iverilog.yml
      - name: Test
        run: |
          cd test && python3 test.py si-p-
  riscv-tests-ua-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_iverilog.yml
      - name: Test
        run: |
          cd test && python3 test.py ua-p-
  riscv-tests-ui-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_iverilog.yml
      - name: Test
        run: |
          cd test && python3 test.py ui-p-
  riscv-tests-ui-v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_iverilog.yml
      - name: Test
        run: |
          cd test && python3 test.py ui-v-
  riscv-tests-um-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_iverilog.yml
      - name: Test
        run: |
          cd test && python3 test.py um-p-
  riscv-tests-um-v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_iverilog.yml
      - name: Test
        run: |
          cd test && python3 test.py um-v-
  verilator-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_verilator.yml
      - name: Lint
        run: |
          cd src
          make v
  coremark-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_verilator.yml
      - name: Test
        run: |
          cd src
          rm -rf obj_dir
          verilator --cc -DDEBUG -DFAST_UART -DOPTION="-DMEM_FILE=\\\"../test/bench/coremark/output/code.bin.aligned\\\"" test_verilator.sv --exe test_kenel_verilator_main.cpp
          make -j -C obj_dir/ -f Vtest_verilator.mk Vtest_verilator
          cd ../.github/workflows
          python3 coremark.py
  chiseltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/install_verilator.yml
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Build and test
        run: |
          cd test/chisel
          ln -s ../../../../../src/ src/test/resources/ 
          sbt test