on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  riscv-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install verilator and iverilog
        run: |
          sudo apt-get -y install verilator iverilog
      - name: Test
        run: |
          cd test && python3 test.py
