name: riscv-tests
run-name: Run riscv-tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  mi-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-iverilog
      - name: Test
        run: |
          cd test && python3 test.py -nodebug mi-p-
  si-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-iverilog
      - name: Test
        run: |
          cd test && python3 test.py -nodebug si-p-
  ua-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-iverilog
      - name: Test
        run: |
          cd test && python3 test.py -nodebug ua-p-
  ui-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-iverilog
      - name: Test
        run: |
          cd test && python3 test.py -nodebug ui-p-
  ui-v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-iverilog
      - name: Test
        run: |
          cd test && python3 test.py -nodebug ui-v-
  um-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-iverilog
      - name: Test
        run: |
          cd test && python3 test.py -nodebug um-p-
  um-v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-iverilog
      - name: Test
        run: |
          cd test && python3 test.py -nodebug um-v-