name: behaviour tests
run-name: Run behaviour tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  verilator-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-verilator
      - name: Lint
        run: |
          cd src
          make v
  coremark-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-verilator
      - name: Test
        run: |
          cd src
          rm -rf obj_dir
          verilator --cc -DDEBUG -DFAST_UART -DMEM_FILE=\"../test/bench/coremark/output/code.bin.aligned\" test_verilator.sv --exe test_kenel_verilator_main.cpp
          make -j -C obj_dir/ -f Vtest_verilator.mk Vtest_verilator
          cd ../.github/workflows
          python3 coremark.py
  chiseltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-verilator
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Build and test
        run: |
          cd test/chisel
          ln -s ../../../../../src/ src/test/resources/ 
          sbt test